"""Unit coverage for `tiny pkg vendor` readme output and lockfile drift checks."""

from __future__ import annotations

from pathlib import Path

import pytest

from tiny_pkg_cli import main as pkg_main
from tiny_pkg_resolution import manifest_hash_for_path, write_lockfile


def _write_manifest(manifest_path: Path, *, dependency_version: str) -> None:
    manifest_path.write_text(
        "\n".join(
            [
                "[package]",
                'name = "demo"',
                'version = "0.1.0"',
                "",
                "[dependencies]",
                f'dep = {{ path = "deps/dep", version = "{dependency_version}" }}',
                "",
            ]
        ),
        encoding="utf-8",
    )


def _create_dependency_root(root: Path) -> None:
    dependency_root = root / "deps" / "dep"
    dependency_root.mkdir(parents=True, exist_ok=True)
    (dependency_root / "README.md").write_text("dependency content\n", encoding="utf-8")


def test_pkg_vendor_writes_readme_summary(tmp_path: Path) -> None:
    manifest_path = tmp_path / "tiny.toml"
    _write_manifest(manifest_path, dependency_version="1.2.3")
    _create_dependency_root(tmp_path)
    lock_path = tmp_path / "tiny.lock"
    write_lockfile(lock_path, manifest_path)

    exit_code = pkg_main(["vendor", "--manifest", str(manifest_path)])

    assert exit_code == 0
    vendor_root = tmp_path / "vendor"
    readme_path = vendor_root / "README.md"
    assert readme_path.exists()

    readme_text = readme_path.read_text(encoding="utf-8")
    manifest_hash = manifest_hash_for_path(manifest_path)
    assert "This directory was generated by `tiny pkg vendor`." in readme_text
    assert f"- Manifest hash: `{manifest_hash}`" in readme_text
    assert "- `dep` `1.2.3` (path) — deps/dep" in readme_text
    assert (vendor_root / "local" / "dep" / "1.2.3").exists()


def test_pkg_vendor_rejects_lockfile_drift(tmp_path: Path) -> None:
    manifest_path = tmp_path / "tiny.toml"
    _write_manifest(manifest_path, dependency_version="1.0.0")
    _create_dependency_root(tmp_path)
    lock_path = tmp_path / "tiny.lock"
    write_lockfile(lock_path, manifest_path)

    _write_manifest(manifest_path, dependency_version="2.0.0")

    with pytest.raises(SystemExit) as excinfo:
        pkg_main(["vendor", "--manifest", str(manifest_path)])

    assert "Lockfile manifest hash does not match tiny.toml" in str(excinfo.value)
