"""Runtime for executing TinyLanguage native bytecode.

The VM is intentionally small and only covers the subset of opcodes
emitted by ``NativeCodeGenerator``. It keeps a single list-based stack,
maintains per-frame locals, and captures output in memory so tests can
compare interpreter and native results easily.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional

from native_ir import Instruction, Opcode, ProgramIR


@dataclass(frozen=True)
class NamespaceRef:
    name: str


class _Frame:
    """Lightweight execution frame with its own instruction pointer."""

    def __init__(
        self,
        instructions: List[Instruction],
        locals_: Optional[Dict[str, Any]] = None,
        globals_: Optional[Dict[str, Any]] = None,
    ) -> None:
        """Initialise a frame with an instruction list and optional locals."""

        self.instructions = instructions
        self.locals = locals_ if locals_ is not None else {}
        self.globals = globals_ if globals_ is not None else self.locals
        self.ip = 0


class NativeVM:
    """Execute bytecode generated by ``NativeCodeGenerator``."""

    _binary_ops = {
        "+": lambda a, b: a + b,
        "-": lambda a, b: a - b,
        "*": lambda a, b: a * b,
        "/": lambda a, b: a / b,
        "%": lambda a, b: a % b,
        "^": lambda a, b: a**b,
        "==": lambda a, b: a == b,
        "!=": lambda a, b: a != b,
        "<": lambda a, b: a < b,
        ">": lambda a, b: a > b,
        "<=": lambda a, b: a <= b,
        ">=": lambda a, b: a >= b,
        "&&": lambda a, b: bool(a) and bool(b),
        "||": lambda a, b: bool(a) or bool(b),
        "and": lambda a, b: bool(a) and bool(b),
        "or": lambda a, b: bool(a) or bool(b),
    }

    def __init__(
        self,
        *,
        module_resolver: Optional[Any] = None,
        module_namespace: Optional[str] = None,
        module_path: Optional[Path] = None,
    ) -> None:
        self.output: List[str] = []
        self.globals: Dict[str, Any] = {}
        self.program: Optional[ProgramIR] = None
        self.heap: Dict[int, List[Any]] = {}
        self.next_ptr = 1
        self.freed_ptrs: set[int] = set()
        self.freed_allocations: Dict[int, int] = {}
        self.heap_cell_types: Dict[int, Dict[int, str]] = {}
        self.error_message: Optional[str] = None
        self.class_defs: Dict[str, Dict[str, Any]] = {}
        self.operator_overloads: Dict[tuple[str, str, str], str] = {}
        self.module_resolver = module_resolver
        self.module_envs: Dict[str, Dict[str, Any]] = {}
        self.module_programs: Dict[str, ProgramIR] = {}
        self.current_module_namespace = module_namespace
        self.current_module_path = module_path

    def run(self, program: ProgramIR) -> str:
        """Execute the program entry block and return captured output."""

        self.program = program
        self.class_defs = {
            name: {"fields": list(class_def.fields), "bases": list(class_def.bases)}
            for name, class_def in program.classes.items()
        }
        self.operator_overloads = {
            (overload.op, overload.a_type, overload.b_type): overload.func_name
            for overload in program.operator_overloads
        }
        self._execute(_Frame(program.entry, self.globals, self.globals))
        return "".join(self.output)

    def _execute(self, frame: _Frame) -> Any:
        """Interpret instructions inside the given frame until completion."""

        stack: List[Any] = []
        while frame.ip < len(frame.instructions):
            instr = frame.instructions[frame.ip]
            frame.ip += 1

            if instr.op == Opcode.PUSH_CONST:
                stack.append(instr.arg)
            elif instr.op == Opcode.LOAD:
                stack.append(self._load(frame.locals, frame.globals, instr.arg))
            elif instr.op == Opcode.STORE:
                value = stack.pop()
                frame.locals[instr.arg] = value
                if frame.locals is self.globals:
                    self.globals[instr.arg] = value
            elif instr.op == Opcode.BINARY:
                right = stack.pop()
                left = stack.pop()
                overload_key = (
                    instr.arg,
                    self._value_type_name(left),
                    self._value_type_name(right),
                )
                overload_name = self.operator_overloads.get(overload_key)
                if overload_name is not None:
                    stack.append(self._call(overload_name, [left, right]))
                else:
                    op_fn = self._binary_ops.get(instr.arg)
                    if op_fn is None:
                        raise RuntimeError(f"unsupported operator {instr.arg}")
                    stack.append(op_fn(left, right))
            elif instr.op == Opcode.PRINT:
                values = [stack.pop() for _ in range(int(instr.arg))][::-1]
                self.output.append(" ".join(self._format_value(v) for v in values) + "\n")
            elif instr.op == Opcode.FLUSH:
                import sys

                sys.stdout.flush()
            elif instr.op == Opcode.JUMP:
                frame.ip = int(instr.arg)
            elif instr.op == Opcode.JUMP_IF_FALSE:
                cond = stack.pop()
                if not cond:
                    frame.ip = int(instr.arg)
            elif instr.op == Opcode.CALL:
                name, argc = instr.arg
                args = [stack.pop() for _ in range(argc)][::-1]
                stack.append(self._call(name, args))
            elif instr.op == Opcode.POP:
                stack.pop()
            elif instr.op == Opcode.RETURN:
                return stack.pop() if stack else None
            else:
                op_name = instr.op.value if isinstance(instr.op, Opcode) else str(instr.op)
                supported = ", ".join(op.value for op in Opcode)
                raise RuntimeError(f"unknown opcode {op_name}. Supported opcodes: {supported}.")
        return None

    def _load(self, locals_: Dict[str, Any], globals_: Dict[str, Any], name: str) -> Any:
        """Resolve a variable name from locals or globals, raising on miss."""

        if name == "errorMessage":
            return self.error_message
        if name in locals_:
            return locals_[name]
        if name in globals_:
            return globals_[name]
        raise RuntimeError(f"unknown variable {name}")

    def _call(self, name: str, args: List[Any]) -> Any:
        """Invoke a function declared in the program with positional args."""

        if name == "__import":
            if len(args) != 1:
                raise RuntimeError(f"__import expects 1 arg, got {len(args)}")
            return self._import_module(args[0])
        if name in {"__new", "new"}:
            if len(args) != 1:
                raise RuntimeError(f"{name} expects 1 arg, got {len(args)}")
            return self._heap_new(args[0])
        if name == "heap_get":
            if len(args) != 2:
                raise RuntimeError(f"heap_get expects 2 args, got {len(args)}")
            return self._heap_get(args[0], args[1])
        if name == "heap_set":
            if len(args) != 3:
                raise RuntimeError(f"heap_set expects 3 args, got {len(args)}")
            return self._heap_set(args[0], args[1], args[2])
        if name == "delete":
            if len(args) != 1:
                raise RuntimeError(f"delete expects 1 arg, got {len(args)}")
            return self._heap_delete(args[0])
        if name == "__class_new":
            return self._class_new(args)
        if name == "__field_get":
            if len(args) != 2:
                raise RuntimeError(f"__field_get expects 2 args, got {len(args)}")
            return self._field_get(args[0], args[1])
        if name == "__field_set":
            if len(args) != 3:
                raise RuntimeError(f"__field_set expects 3 args, got {len(args)}")
            return self._field_set(args[0], args[1], args[2])
        if name == "__method_call":
            if len(args) < 2:
                raise RuntimeError("__method_call expects at least 2 args")
            return self._method_call(args[0], args[1], args[2:])
        if self.program is None:
            raise RuntimeError("VM has no program loaded")
        target = self.program.functions.get(name)
        if target is None:
            raise RuntimeError(f"unknown function {name}")
        if len(args) != len(target.params):
            raise RuntimeError(f"function {name} expects {len(target.params)} args, got {len(args)}")
        locals_ = dict(zip(target.params, args))
        return self._execute(_Frame(target.instructions, locals_, self._globals_for_function(name)))

    def _format_value(self, value: Any) -> str:
        """Render VM values into the textual form used by PRINT."""

        if value is None:
            return "null"
        if isinstance(value, bool):
            return "true" if value else "false"
        return str(value)

    def _record_error(self, message: str) -> None:
        self.error_message = message

    def _globals_for_function(self, name: str) -> Dict[str, Any]:
        module_name = self._module_namespace_for_function(name)
        if module_name:
            return self.module_envs[module_name]
        return self.globals

    def _module_namespace_for_function(self, name: str) -> Optional[str]:
        if not self.module_envs or "." not in name:
            return None
        candidates = [ns for ns in self.module_envs if name.startswith(f"{ns}.")]
        if not candidates:
            return None
        return max(candidates, key=len)

    def _import_module(self, name: Any) -> NamespaceRef:
        if self.module_resolver is None:
            raise RuntimeError("module resolver not configured for native backend")
        return self.module_resolver.import_module(
            str(name),
            self,
            caller_namespace=self.current_module_namespace,
            caller_path=self.current_module_path,
        )

    def load_module(self, name: str, program: ProgramIR, module_env: Dict[str, Any], module_path: Path | None) -> None:
        if self.program is None:
            raise RuntimeError("VM has no program loaded")
        self.program.functions.update(program.functions)
        self.program.classes.update(program.classes)
        self.program.operator_overloads.extend(program.operator_overloads)
        for overload in program.operator_overloads:
            self.operator_overloads[(overload.op, overload.a_type, overload.b_type)] = overload.func_name
        self.module_envs[name] = module_env
        self.module_programs[name] = program
        previous_namespace = self.current_module_namespace
        previous_path = self.current_module_path
        try:
            self.current_module_namespace = name
            self.current_module_path = module_path
            self._execute(_Frame(program.entry, module_env, module_env))
        finally:
            self.current_module_namespace = previous_namespace
            self.current_module_path = previous_path

    @staticmethod
    def _pointer_label(pointer: Any) -> str:
        type_name = type(pointer).__name__
        if isinstance(pointer, (int, float)) and str(pointer).isnumeric():
            return str(int(pointer))
        return f"{pointer!r} ({type_name})"

    def _parse_heap_index(self, index: Any) -> Optional[int]:
        try:
            idx = int(index)
        except Exception:
            message = f"heap access error: index {index!r} is not numeric"
            self._record_error(message)
            return None
        if isinstance(index, float) and not index.is_integer():
            message = f"heap access error: index {self._pointer_label(index)} is not an integer index"
            self._record_error(message)
            return None
        return idx

    def _resolve_ptr(self, pointer: Any, *, op: str) -> Optional[tuple[int, List[Any]]]:
        try:
            ip = int(pointer)
        except Exception:
            message = f"heap {op} error: pointer {self._pointer_label(pointer)} is not numeric"
            self._record_error(message)
            return None
        if isinstance(pointer, float) and not pointer.is_integer():
            message = f"heap {op} error: pointer {self._pointer_label(pointer)} is not an integer pointer"
            self._record_error(message)
            return None
        if ip < 1:
            message = f"heap {op} error: pointer {ip} is invalid (must refer to a live positive allocation)"
            self._record_error(message)
            return None
        if ip in self.freed_ptrs:
            size_part = self.freed_allocations.get(ip)
            size_hint = f" (size {size_part})" if size_part is not None else ""
            message = f"heap {op} error: pointer {ip} was already freed{size_hint}"
            self._record_error(message)
            return None
        try:
            cells = self.heap[ip]
        except KeyError:
            live = sorted(self.heap.keys())
            freed = sorted(self.freed_ptrs)
            details: List[str] = []
            if live:
                details.append(f"live: {live}")
            if freed:
                details.append(f"freed: {freed}")
            context = f" ({'; '.join(details)})" if details else ""
            message = f"heap {op} error: unknown pointer {ip}{context}"
            self._record_error(message)
            return None
        return ip, cells

    def _heap_new(self, size: Any) -> int:
        count = int(size)
        if count < 0:
            raise RuntimeError("alloc error: negative size")
        ptr = self.next_ptr
        self.next_ptr += 1
        self.heap[ptr] = [0 for _ in range(count)]
        self.freed_ptrs.discard(ptr)
        self.freed_allocations.pop(ptr, None)
        self.heap_cell_types.pop(ptr, None)
        return ptr

    def _value_type_name(self, value: Any) -> str:
        if isinstance(value, dict):
            if "__type__" in value:
                return str(value.get("__type__"))
            if "__tag__" in value:
                return str(value.get("__tag__"))
        if value is None:
            return "Null"
        if isinstance(value, bool):
            return "Bool"
        if isinstance(value, int) and not isinstance(value, bool):
            return "int"
        if isinstance(value, float):
            return "float"
        if isinstance(value, str):
            return "string"
        return type(value).__name__

    @staticmethod
    def _heap_ok_record() -> Dict[str, Any]:
        return {"__tag__": "Record", "e": {"__tag__": "Error", "code": 0, "msg": ""}}

    def _heap_error_record(self, message: str) -> Dict[str, Any]:
        return {"__tag__": "Record", "e": {"__tag__": "Error", "code": 1, "msg": message}}

    def _heap_delete(self, pointer: Any) -> Dict[str, Any]:
        resolved = self._resolve_ptr(pointer, op="delete")
        if resolved is None:
            return self._heap_error_record(self.error_message or "")
        ip, cells = resolved
        size = len(cells)
        self.heap.pop(ip, None)
        self.heap_cell_types.pop(ip, None)
        self.freed_ptrs.add(ip)
        self.freed_allocations[ip] = size
        return self._heap_ok_record()

    def _heap_get(self, pointer: Any, index: Any) -> Any:
        idx = self._parse_heap_index(index)
        if idx is None:
            return None
        resolved = self._resolve_ptr(pointer, op="access")
        if resolved is None:
            return None
        ip, cells = resolved
        size = len(cells)
        if idx < 0 or idx >= size:
            range_hint = "empty allocation" if size == 0 else f"valid indices: 0..{size - 1}"
            message = f"heap access error: index {idx} out of range for pointer {ip} (size {size}; {range_hint})"
            self._record_error(message)
            return None
        return cells[idx]

    def _heap_set(self, pointer: Any, index: Any, value: Any) -> Dict[str, Any]:
        idx = self._parse_heap_index(index)
        if idx is None:
            return self._heap_error_record(self.error_message or "")
        resolved = self._resolve_ptr(pointer, op="access")
        if resolved is None:
            return self._heap_error_record(self.error_message or "")
        ip, cells = resolved
        size = len(cells)
        if idx < 0 or idx >= size:
            range_hint = "empty allocation" if size == 0 else f"valid indices: 0..{size - 1}"
            message = f"heap access error: index {idx} out of range for pointer {ip} (size {size}; {range_hint})"
            self._record_error(message)
            return self._heap_error_record(message)
        expected = self.heap_cell_types.get(ip, {}).get(idx)
        actual = self._value_type_name(value)
        if expected is not None and expected != actual:
            message = f"heap type mismatch at {ip}[{idx}]: expected {expected} but got {actual}"
            self._record_error(message)
            return self._heap_error_record(message)
        cells[idx] = value
        self.heap_cell_types.setdefault(ip, {})[idx] = actual
        return self._heap_ok_record()

    def _class_mro(self, name: str) -> List[str]:
        info = self.class_defs.get(name)
        if info is None:
            raise RuntimeError(f"unknown class {name}")
        bases = list(info.get("bases", []))
        mro: List[str] = [name]
        for base in bases:
            if base not in self.class_defs:
                raise RuntimeError(f"unknown base class {base} for {name}")
            for ancestor in self._class_mro(base):
                if ancestor not in mro:
                    mro.append(ancestor)
        return mro

    def _class_field_map(self, name: str) -> Dict[str, Dict[str, Any]]:
        mro = self._class_mro(name)
        fields: Dict[str, Dict[str, Any]] = {}
        for cls in mro:
            class_info = self.class_defs.get(cls)
            if class_info is None:
                raise RuntimeError(f"unknown class {cls}")
            field_names = class_info.get("fields", [])
            fields[cls] = {fname: None for fname in field_names}
        return fields

    @staticmethod
    def _split_field_name(field_name: str) -> tuple[Optional[str], str]:
        if "." in field_name:
            owner, rest = field_name.split(".", 1)
            return owner, rest
        return None, field_name

    def _resolve_field_storage(
        self, obj: Dict[str, Any], field_name: str, owner_hint: Optional[str], *, allow_write: bool
    ) -> Dict[str, Any]:
        current_class = obj.get("__tag__")
        if current_class is None:
            raise RuntimeError("field access on untagged value")
        mro = self._class_mro(str(current_class))
        matches: List[tuple[str, Dict[str, Any]]] = []
        for cls in mro:
            fmap = obj["__fields__"].get(cls, {})
            if field_name in fmap:
                matches.append((cls, fmap))

        if owner_hint:
            for cls, fmap in matches:
                if cls == owner_hint:
                    return fmap
            raise RuntimeError(f"unknown field {field_name} for base class {owner_hint}")

        if matches:
            primary_class = mro[0]
            for cls, fmap in matches:
                if cls == primary_class:
                    return fmap

        if len(matches) == 1:
            return matches[0][1]
        if len(matches) > 1:
            action = "assign" if allow_write else "access"
            raise RuntimeError(
                f"ambiguous field {field_name} during {action}; please qualify with a base class name"
            )
        raise RuntimeError(f"unknown field {field_name} for class {current_class}")

    def _class_new(self, args: List[Any]) -> Dict[str, Any]:
        if not args:
            raise RuntimeError("__class_new expects at least 1 arg")
        class_name = str(args[0])
        if class_name not in self.class_defs:
            raise RuntimeError(f"unknown class {class_name}")
        if (len(args) - 1) % 2 != 0:
            raise RuntimeError("__class_new expects field name/value pairs")
        obj: Dict[str, Any] = {"__tag__": class_name, "__fields__": self._class_field_map(class_name)}
        for index in range(1, len(args), 2):
            raw_name = str(args[index])
            value = args[index + 1]
            owner_hint, field_name = self._split_field_name(raw_name)
            fmap = self._resolve_field_storage(obj, field_name, owner_hint, allow_write=True)
            fmap[field_name] = value
        return obj

    def _field_get(self, obj: Any, field_name: Any) -> Any:
        if isinstance(obj, NamespaceRef):
            module_env = self.module_envs.get(obj.name)
            if module_env is None:
                raise RuntimeError(f"unknown module {obj.name}")
            field = str(field_name)
            if field in module_env:
                return module_env[field]
            raise RuntimeError(f"unknown field {field}")
        if not isinstance(obj, dict) or "__fields__" not in obj:
            raise RuntimeError("field access on non-class value")
        owner_hint, fname = self._split_field_name(str(field_name))
        fmap = self._resolve_field_storage(obj, fname, owner_hint, allow_write=False)
        return fmap[fname]

    def _field_set(self, obj: Any, field_name: Any, value: Any) -> Any:
        if isinstance(obj, NamespaceRef):
            raise RuntimeError("field access on module namespace")
        if not isinstance(obj, dict) or "__fields__" not in obj:
            raise RuntimeError("field access on non-class value")
        owner_hint, fname = self._split_field_name(str(field_name))
        fmap = self._resolve_field_storage(obj, fname, owner_hint, allow_write=True)
        fmap[fname] = value
        return value

    def _method_call(self, obj: Any, method_name: Any, args: List[Any]) -> Any:
        if self.program is None:
            raise RuntimeError("VM has no program loaded")
        if isinstance(obj, NamespaceRef):
            qualified = f"{obj.name}.{method_name}"
            return self._call(qualified, list(args))
        if not isinstance(obj, dict) or "__fields__" not in obj:
            raise RuntimeError("method call on non-class value")
        class_name = obj.get("__tag__")
        if class_name is None:
            raise RuntimeError("method call on untagged value")
        method_name = str(method_name)
        for cls in self._class_mro(str(class_name)):
            target_name = f"{cls}.{method_name}"
            target = self.program.functions.get(target_name)
            if target is None:
                continue
            method_args = [obj] + list(args)
            if len(method_args) != len(target.params):
                raise RuntimeError(
                    f"method {target_name} expects {len(target.params)} args, got {len(method_args)}"
                )
            locals_ = dict(zip(target.params, method_args))
            return self._execute(_Frame(target.instructions, locals_))
        raise RuntimeError(f"no method {method_name} for class {class_name}")
